Add 1.0.4 commands to encoding
ivajloip/rust-lorawan pull request #107
Opened 2023-04-26 09:59 UTC by lucasgranberg

Adding the commands makes it easier to develop towards 1.0.4. As I added them here even 1.0.2 projects would have the new commands. Ideally these new commands could be behind a feature but that is not so easy to implement with the current macros.

2023-04-26 11:25 UTC, lulf approved these changes
LGTM!

2023-04-27 20:04 UTC, ivajloip requested changes
Thank for implementing those newer mac commands! This is really appreciated! I added a few things to double check, but otherwise it looks good to me! :slightly_smiling_face:

2023-04-27 20:04 UTC, ivajloip commented on encoding/tests/maccommandcreator.rs
> +#[test]
nit: New line missing here and below.

2023-04-28 06:01 UTC, lucasgranberg commented on encoding/src/maccommandcreator.rs
> +    }
yep you are right, I read that wrong, max_eirp is 4 bits 3:0 according to the spec

2023-04-28 06:03 UTC, lucasgranberg commented on encoding/src/maccommands.rs
> +        self.0[0] & (1 << 3) != 0
yep, brain fart continues from max eirp

2023-04-28 19:01 UTC, ivajloip approved these changes
Thanks! :slightly_smiling_face:

2023-05-01 09:10 UTC, merged